<?php
// Replaces HomeFrame.initContentDatabase() + getMediaDescription()
function catalog(): array {
    $M = '#1F75FE'; $W = '#9B51E0'; $G = '#00A896'; $A = '#FF7B00';
    $nf = fn($q, $id) => "https://www.netflix.com/search?q=$q&jbv=$id";
    return [
        // Movies
        ['id'=>101,'title'=>'Forgotten Island','category'=>'Movie','badge'=>'Movie Only','base'=>'#7F5A83','badgeColor'=>$M,'image'=>'https://i.ytimg.com/vi/a8RHqN93qfo/maxresdefault.jpg','trailer'=>'https://youtu.be/f7mFVeWnVLw?si=ILWRPAS83DPUTfTa','stream'=>null,'desc'=>'Two friends discover a mysterious island filled with strange secrets, dangerous surprises, and a story that changes everything they thought they knew.'],
        ['id'=>102,'title'=>'Spider-Man: No Way Home','category'=>'Movie','badge'=>'Movie Only','base'=>'#B83B5E','badgeColor'=>$M,'image'=>'https://i.ytimg.com/vi/6WrNoNra_2U/maxresdefault.jpg','trailer'=>'https://www.youtube.com/watch?v=JfVOs4VSpmA','stream'=>null,'desc'=>"Peter Parker's identity is revealed, causing his life to become chaotic. He seeks help to restore his secret while facing unexpected threats from other worlds."],
        ['id'=>103,'title'=>'MEG 2: The Trench','category'=>'Movie','badge'=>'Movie Only','base'=>'#134E5E','badgeColor'=>$M,'image'=>'https://i.ytimg.com/vi/APAxQKPUhi8/maxresdefault.jpg','trailer'=>'https://www.youtube.com/watch?v=dG91B3hHyY4','stream'=>'https://www.netflix.com/watch/80237937','desc'=>'A research team ventures into the deepest parts of the ocean and encounters enormous prehistoric creatures while fighting to survive the dangerous expedition.'],
        ['id'=>104,'title'=>'The Conjuring','category'=>'Movie','badge'=>'Movie Only','base'=>'#3A1E34','badgeColor'=>$M,'image'=>'https://i.ytimg.com/vi/ejMMn0t58Lc/maxresdefault.jpg','trailer'=>'https://www.youtube.com/watch?v=ejMMn0t58Lc','stream'=>null,'desc'=>"A family moves into an isolated farmhouse and soon experiences disturbing supernatural events, leading paranormal investigators to uncover the home's dark history."],
        ['id'=>105,'title'=>'Project Hail Mary','category'=>'Movie','badge'=>'Movie Only','base'=>'#1A434A','badgeColor'=>$M,'image'=>'https://i.ytimg.com/vi/m08TxIsFTRI/maxresdefault.jpg','trailer'=>'https://www.youtube.com/watch?v=m08TxIsFTRI','stream'=>null,'desc'=>'A lone astronaut awakens far from Earth with a crucial mission to save humanity, forcing him to solve a mystery that could determine the future of the planet.'],
        // Manhwa
        ['id'=>201,'title'=>'Solo Leveling','category'=>'Manhwa','badge'=>'Webtoon','base'=>'#1B2A47','badgeColor'=>$W,'image'=>'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-D_1KYEkprBip6jN3FWXvRhxAEFkgVQ498cDrmUK7La-rJzMkGgraszM&s=10','trailer'=>'https://youtu.be/bssSj4cKsrI','stream'=>'https://mangadex.org/title/32d76d19-8a05-4db0-9fc2-e0b0648fe9d0/na-honjaman-level-up','desc'=>'Sung Jinwoo, once considered the weakest hunter, gains a mysterious ability that allows him to grow stronger and face increasingly powerful enemies.'],
        ['id'=>202,'title'=>'Tower Of God','category'=>'Manhwa','badge'=>'Webtoon','base'=>'#7B3E19','badgeColor'=>$W,'image'=>'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdwl92tf6_nBR5TYLh2Qg2Asq12U8-1RqeWWTCrkmPYNHIRlTSYOfTr4F1&s=10','trailer'=>'https://youtu.be/NlS4Eceev-4','stream'=>'https://mangadex.org/title/c0ee660b-f9f2-45c3-8068-5123ff53f84a/sinui-tap','desc'=>'Bam enters the mysterious Tower in search of the only person he cares about and must overcome dangerous tests, powerful rivals, and hidden secrets.'],
        ['id'=>203,'title'=>'The Greatest Estate Developer','category'=>'Manhwa','badge'=>'Webtoon','base'=>'#275D38','badgeColor'=>$W,'image'=>'https://thekmeal.com/wp-content/uploads/2024/01/the-greatest-estate-developer-chapter-116-release-date-raw-scan-spoilers-and-more-655b1aefa84d370106238-1200.webp','trailer'=>'https://youtu.be/q9aSiQsh5fU','stream'=>'https://mangadex.org/title/d7f56ace-cd30-48b9-8b64-afeca0077fca/yeokdaegeum-yeongji-seolgyesa','desc'=>'A civil engineering student wakes up inside a fantasy novel and uses his knowledge, creativity, and questionable schemes to transform a struggling estate.'],
        ['id'=>204,'title'=>'Eleceed','category'=>'Manhwa','badge'=>'Webtoon','base'=>'#8C3A27','badgeColor'=>$W,'image'=>'https://a.storyblok.com/f/178900/960x540/6567aeb36a/eleceed-header.png','trailer'=>'https://youtu.be/srhNKNytU8c','stream'=>'https://mangadex.org/title/7e544761-7d3d-4fce-8137-719814d7d138/eleceed','desc'=>'Jiwoo discovers a hidden world of powerful awakened individuals while forming an unlikely friendship with a mysterious mentor who takes the form of a cat.'],
        ['id'=>205,'title'=>'Palace Gown','category'=>'Manhwa','badge'=>'Webtoon','base'=>'#612547','badgeColor'=>$W,'image'=>null,'trailer'=>null,'stream'=>null,'desc'=>'A gripping webtoon tale filled with drama, court intrigue, and personal ambition.'],
        // Manga
        ['id'=>301,'title'=>'Vagabond','category'=>'Manga','badge'=>'Manga','base'=>'#36382E','badgeColor'=>$G,'image'=>'https://i.ytimg.com/vi/8hPZeLNxjVU/maxresdefault.jpg','trailer'=>'','stream'=>'https://mangadex.org/title/d1a9fdeb-f713-407f-960c-8326b586e6fd/vagabond','desc'=>'A wandering swordsman travels through a violent era of Japanese history, seeking strength and purpose while confronting powerful warriors and his own beliefs.'],
        ['id'=>302,'title'=>'Goodnight Punpun','category'=>'Manga','badge'=>'Manga','base'=>'#283618','badgeColor'=>$G,'image'=>'https://i.pinimg.com/564x/07/02/86/07028636e3664154ca4bfa90575da479.jpg','trailer'=>'','stream'=>'https://mangadex.org/title/4301d363-ee02-43f4-ae24-4cbf29a74830/oyasumi-punpun','desc'=>'Punpun grows up while struggling with family problems, relationships, loneliness, and the difficult transition from childhood into adulthood.'],
        ['id'=>303,'title'=>'20th Century Boys','category'=>'Manga','badge'=>'Manga','base'=>'#603813','badgeColor'=>$G,'image'=>'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEj4_gkz9VyVNe15pTTIj7VDpBCVkjuqkg0-2SP6CzJLmi4gNWriip6McL4nyF5qiSVfiE1o9LFbknwTCotw194ihTyfHp187lsT6YFnIqxpHsrTTyuPPg5iz6bKZKabDttoolGascqQMHB4/s1600/20thCenturyBoys1.jpg','trailer'=>'','stream'=>'https://mangadex.org/title/ad06790a-01e3-400c-a449-0ec152d6756a/20th-century-boys','desc'=>'A group of childhood friends discovers that a mysterious cult leader is recreating events from their old childhood predictions, putting the future of humanity at risk.'],
        ['id'=>304,'title'=>'Yotsuba!','category'=>'Manga','badge'=>'Manga','base'=>'#3D5A80','badgeColor'=>$G,'image'=>'https://cdna.artstation.com/p/assets/images/images/078/635/588/large/healbound-asset.jpg','trailer'=>'','stream'=>'https://mangadex.org/title/58be6aa6-06cb-4ca5-bd20-f1392ce451fb/yotsuba-to','desc'=>'Yotsuba is an energetic and curious young girl who finds excitement in ordinary everyday experiences, bringing humor and joy to everyone around her.'],
        ['id'=>305,'title'=>'Fire Punch','category'=>'Manga','badge'=>'Manga','base'=>'#780000','badgeColor'=>$G,'image'=>'https://de7i3bh7bgh0d.cloudfront.net/2019/10/18/20/16/26/f1b5d4a7-1fc5-40fb-b353-1f541bde4e7a/FP_blogsplash_1200x630v2.jpg','trailer'=>'','stream'=>'https://mangadex.org/title/6fef1f74-a0ad-4f0d-99db-d32a7cd24098/fire-punch','desc'=>'In a frozen world where powerful abilities shape society, a young survivor searches for answers and revenge after a devastating event changes his life.'],
        // Anime
        ['id'=>401,'title'=>'Bleach','category'=>'Anime','badge'=>'Anime','base'=>'#2B2D42','badgeColor'=>$A,'image'=>'https://shop.viz.com/cdn/shop/collections/VIZ_CollectionBanner_BleachTYBW-desktop.jpg','trailer'=>'https://youtu.be/Hb57fdPj7LU','stream'=>$nf('bleach',70204957),'desc'=>'Ichigo Kurosaki gains the powers of a Soul Reaper and is drawn into a hidden world filled with spirits, dangerous enemies, and supernatural battles.'],
        ['id'=>402,'title'=>'Attack on Titan','category'=>'Anime','badge'=>'Anime','base'=>'#540D6E','badgeColor'=>$A,'image'=>'https://anitrendz.net/news/wp-content/uploads/2023/03/attack-on-titan-uniqlo-web-banner.jpg','trailer'=>'https://youtu.be/MGRm4IzK1SQ','stream'=>$nf('attack%20on%20titan',70299043),'desc'=>'Humanity struggles to survive behind enormous walls while mysterious Titans threaten their existence, forcing young soldiers to uncover the truth behind their world.'],
        ['id'=>403,'title'=>'Fullmetal Alchemist','category'=>'Anime','badge'=>'Anime','base'=>'#8A181A','badgeColor'=>$A,'image'=>'https://cms-cdn.rhinoshield.app/public/images/FM_crossover_banner_1800_aa5b501dff.jpg','trailer'=>'https://youtu.be/-GoNo0DGroU','stream'=>$nf('full%20metal',81266975),'desc'=>'Two brothers use alchemy in their search to restore what they lost, becoming involved in a larger conspiracy that threatens the entire country.'],
        ['id'=>404,'title'=>'Jujutsu Kaisen','category'=>'Anime','badge'=>'Anime','base'=>'#1F2041','badgeColor'=>$A,'image'=>'https://i.pinimg.com/736x/28/ef/40/28ef40e53d0036c906c3f7ce5445754f.jpg','trailer'=>'https://youtu.be/pkKu9hLT-t8','stream'=>$nf('jujutsu',81278456),'desc'=>'Yuji Itadori becomes involved with the world of cursed spirits after a dangerous encounter, joining sorcerers who fight supernatural threats.'],
        ['id'=>405,'title'=>'One Piece','category'=>'Anime','badge'=>'Anime','base'=>'#023E8A','badgeColor'=>$A,'image'=>'https://a.storyblok.com/f/178900/960x540/d8dc62ca3d/luffy-one-piece-25th-anniversary-banner.png','trailer'=>'https://youtu.be/3Gmo0EXHyKg','stream'=>$nf('one%20piece',80107103),'desc'=>'Monkey D. Luffy sets out across the seas with his crew in search of the legendary One Piece while pursuing his dream of becoming the Pirate King.'],
    ];
}
